name: ci-cd 

on:
  push:
    branches:
      - main

env:
  ECR_REGISTRY: 371410071971.dkr.ecr.us-west-2.amazonaws.com
  AWS_REGION: us-west-2

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and tag Docker image
        run: |
          docker build -t $ECR_REGISTRY/lambda-weather-img:staging .
          docker tag $ECR_REGISTRY/lambda-weather-img:staging $ECR_REGISTRY/lambda-weather-img:staging

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/lambda-weather-img:staging

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name daily-weather-staging --image-uri $ECR_REGISTRY/lambda-weather-img:staging

      - name: Test Lambda
        run: |
          aws lambda invoke --function-name daily-weather-staging --payload '{}' output.json
          cat output.json
          grep -q "null" output.json && echo "No errors found" || exit 1
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and tag Docker image
        run: |
          docker build -t $ECR_REGISTRY/lambda-weather-img:production .
          docker tag $ECR_REGISTRY/lambda-weather-img:production $ECR_REGISTRY/lambda-weather-img:production

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/lambda-weather-img:production

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name daily-weather --image-uri $ECR_REGISTRY/lambda-weather-img:production
    