name: Push to ECR

on:
  push:
    branches:
      - main

env:
  ECR_REGISTRY: 371410071971.dkr.ecr.us-west-2.amazonaws.com
  AWS_REGION: us-west-2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and tag Docker image
        run: |
          docker build -t $ECR_REGISTRY/lambda-weather-img:latest .
          docker tag $ECR_REGISTRY/lambda-weather-img:latest $ECR_REGISTRY/lambda-weather-img:latest

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/lambda-weather-img:latest

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name daily-weather --image-uri $ECR_REGISTRY/lambda-weather-img:latest
